export const SELECT_EVENT = 'SELECT_EVENT';
export const SET_EVENT_TO_FAVORITES = 'SET_EVENT_TO_FAVORITES';
export const ADD_EVENT_TO_FAVORITES = 'ADD_EVENT_TO_FAVORITES';
export const REMOVE_EVENT_FROM_FAVORITES = 'REMOVE_EVENT_FROM_FAVORITES';
